baseURL: "/"
languageCode: "en-us"
title: "Angie's Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
#     - identifier: blog
#       name: Blog
#       title: Blog posts
#       url: /blogs
#       weight: 1
#     - identifier: gallery
#       name: Gallery
#       title: Blog posts
#       url: /gallery
#       weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Angela Mugo"
  description: "Hi, I am Angie!"
  # staticPath: ""  # The path to serve the static files from
  favicon: "/Avatar.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    # brandName: "Hugo Profile" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Angela."
    subtitle: "I build things for iOS, Android, MacOS and all apple platforms "
    content: "A passionate mobile developer. I am currently exploring building fun whimsical products."
    image: "/Avatar.png"
    bottomImage:
      enable: true
    roundImage: true
    button:
      enable: true
      name: "Resume"
      url: "/Angela_Mugo_Resume"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: "https://github.com/angiemugo/"
        - icon: fab fa-x-twitter
          url: https://twitter.com/angien_mugo
        - icon: "fab fa-medium"
          url: https://medium.com/@angela.mugo

  # About
  about:
    enable: true
    title: "About Me"
    image: "/programmer_woman.jpg"
    content: |-
      I am a software developer with a passion for mobile development. My approach to product development is centered around the user. 
      I believe in creating highly customizable products to meet the diverse needs of users, especially those who require extensive accomodations. I pay close attention to accessibility, which is made easier by the integration of accessibility features in the native components we use. I am also cautious of dark patterns and believe in acquiring and retaining customers by providing genuine value, rather than making it difficult for them to leave the product.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Flutter"
        - "Dart"
        - "Python"
        - "Swift"
        - "SwiftUI"
        - "Objective-C"

  # Experience
  experience:
    enable: true
    items:
      - job: "Senior Software Developer"
        company: "Shelfy"
        companyUrl: "https://shelfy.africa/"
        date: "Jan 2023 - present"
        content: "I am currently working with a team of 3 other developers to build an image search based market place product. This product uses computer vision to indentify products that users take pictures of and returns all available matches in the database. It also uses an AI powered recommendation algorithm to return similar products and a homepage powered by the users preferences."

      - job: "Senior iOS Developer"
        company: "37 Signals"
        companyUrl: "https://37signals.com/"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: true
        content: |
         I worked on this remote multidisplinary teams to deliver features that served the huge BaseCamp and Hey customer base.

      - job: "Senior iOS Developer"
        company: "SafeBoda"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: true
        content: |
          I joined a team of 4 iOS developers on this ride hailing product team. We built an app with functionalities such as Food delivery, Fintech, Package delivery as well as ride hailing. I also had the experience of mentoring other team members, leading a team as well as onboarding new team members. 

      - job: "Software Engineer"
        company: "Andela"
        companyUrl: https://www.andela.com/"
        date: "June 2017 - Nov 2019"
        content: |
          I first started software development at this fastpaced and amazing incubator-like institituion. Here I had the experience of working in remote teams all over the worls. I got a chance to work in fields such as Agriculture, music and many others. 

  # projects
  projects:
    enable: true
    items:
      - title: Exercism MacOS
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: "/exercism.png"
        featured:
          name: Demo
          link: https://testflight.apple.com/join/iahVRtO4
        badges:
          - "SwiftUI"
          - "AsyncAwait"
          - "Combine"
          - "AppKit"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile

      - title: Every brilliant thing 
        content: A boy begins listing small, brilliant things that bring him joy in an effort to save his mom from committing suicide. My unique interpretation reimagines this narrative through a gamified Flutter app, designed to add little sparks of hope to your day.
        image: "/EBT.jpg"
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Flutter"
          - "Dart"
          - "Flame"
          - "Bloc"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter


  #Contact
  contact:
    enable: true
    title: "Wanna chat?"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:mugoangela@gmail.com
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: meojwgre # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    socialNetworks:
      github: https://github.com/angiemugo
      linkedin: https://linkedin.com/in/angienmugo


  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>